export const MOCK_TOKEN = "MOCK_TOKEN_12345";

export const mockUserDetails = {
  roll: "RA2211026010000",
  name: "MOCK USER",
  program: "B.Tech",
  department: "Computer Science and Engineering",
  specialisation: "Core",
  semester: "6",
  batch: "1",
  section: "A1",
};

export const mockAttendance = [
  {
    code: "21CSC302J",
    title: "Computer Networks",
    category: "Professional Core",
    faculty: "Dr. Mock Faculty",
    slot: "A1",
    conducted: 40,
    absent: 4,
    percetage: "90.00",
    margin: 6,
  },
  {
    code: "21CSC303J",
    title: "Software Engineering",
    category: "Professional Core",
    faculty: "Dr. Mock Faculty 2",
    slot: "B1",
    conducted: 35,
    absent: 0,
    percetage: "100.00",
    margin: 8,
  },
  {
    code: "21CSC304J",
    title: "Artificial Intelligence",
    category: "Professional Core",
    faculty: "Dr. Mock Faculty 3",
    slot: "C1",
    conducted: 38,
    absent: 2,
    percetage: "94.73",
    margin: 5,
  },
  {
    code: "21CSC305J",
    title: "Database Management Systems",
    category: "Professional Core",
    faculty: "Dr. Mock Faculty 4",
    slot: "D1",
    conducted: 42,
    absent: 6,
    percetage: "85.71",
    margin: 4,
  },
  {
    code: "21CSC306J",
    title: "Operating Systems",
    category: "Professional Core",
    faculty: "Dr. Mock Faculty 5",
    slot: "E1",
    conducted: 40,
    absent: 1,
    percetage: "97.50",
    margin: 7,
  },
  {
    code: "21CSC307J",
    title: "Web Programming",
    category: "Professional Core",
    faculty: "Dr. Mock Faculty 6",
    slot: "F1",
    conducted: 36,
    absent: 5,
    percetage: "86.11",
    margin: 3,
  },
];

export const mockTimetable = {
  "0": {
    "08:00 - 08:50": {
      title: "Computer Networks",
      code: "21CSC302J",
      type: "Theory",
      room: "TP101",
      credit: "4",
    },
    "08:50 - 09:40": {
      title: "Software Engineering",
      code: "21CSC303J",
      type: "Theory",
      room: "TP101",
      credit: "4",
    },
    "09:45 - 10:35": {
      title: "Artificial Intelligence",
      code: "21CSC304J",
      type: "Theory",
      room: "TP102",
      credit: "4",
    },
    "10:40 - 11:30": {
      title: "Database Management Systems",
      code: "21CSC305J",
      type: "Theory",
      room: "TP102",
      credit: "4",
    },
    "11:35 - 12:25": {
      title: "Operating Systems",
      code: "21CSC306J",
      type: "Theory",
      room: "TP103",
      credit: "4",
    },
  },
  "1": {
    "08:00 - 08:50": {
      title: "Web Programming",
      code: "21CSC307J",
      type: "Theory",
      room: "TP205",
      credit: "4",
    },
    "08:50 - 09:40": {
      title: "Web Programming",
      code: "21CSC307J",
      type: "Theory",
      room: "TP205",
      credit: "4",
    },
    "09:45 - 10:35": {
      title: "Computer Networks Lab",
      code: "21CSC302J",
      type: "LAB",
      room: "TP201",
      credit: "4",
    },
    "10:40 - 11:30": {
      title: "Computer Networks Lab",
      code: "21CSC302J",
      type: "LAB",
      room: "TP201",
      credit: "4",
    },
    "11:35 - 12:25": {
      title: "Software Engineering Lab",
      code: "21CSC303J",
      type: "LAB",
      room: "TP202",
      credit: "4",
    },
  },
  "2": {
    "08:00 - 08:50": {
      title: "Artificial Intelligence",
      code: "21CSC304J",
      type: "Theory",
      room: "TP102",
      credit: "4",
    },
    "08:50 - 09:40": {
      title: "Database Management Systems",
      code: "21CSC305J",
      type: "Theory",
      room: "TP102",
      credit: "4",
    },
    "09:45 - 10:35": {
      title: "Operating Systems",
      code: "21CSC306J",
      type: "Theory",
      room: "TP103",
      credit: "4",
    },
    "10:40 - 11:30": {
      title: "Operating Systems",
      code: "21CSC306J",
      type: "Theory",
      room: "TP103",
      credit: "4",
    },
    "11:35 - 12:25": {
      title: "Computer Networks",
      code: "21CSC302J",
      type: "Theory",
      room: "TP101",
      credit: "4",
    },
  },
  "3": {
    "08:00 - 08:50": {
      title: "Artificial Intelligence Lab",
      code: "21CSC304J",
      type: "LAB",
      room: "AI Lab 1",
      credit: "4",
    },
    "08:50 - 09:40": {
      title: "Artificial Intelligence Lab",
      code: "21CSC304J",
      type: "LAB",
      room: "AI Lab 1",
      credit: "4",
    },
    "09:45 - 10:35": {
      title: "Web Programming Lab",
      code: "21CSC307J",
      type: "LAB",
      room: "Web Lab",
      credit: "4",
    },
    "10:40 - 11:30": {
      title: "Web Programming Lab",
      code: "21CSC307J",
      type: "LAB",
      room: "Web Lab",
      credit: "4",
    },
    "11:35 - 12:25": {
      title: "Software Engineering",
      code: "21CSC303J",
      type: "Theory",
      room: "TP101",
      credit: "4",
    },
  },
  "4": {
    "08:00 - 08:50": {
      title: "Database Management Systems Lab",
      code: "21CSC305J",
      type: "LAB",
      room: "DB Lab",
      credit: "4",
    },
    "08:50 - 09:40": {
      title: "Database Management Systems Lab",
      code: "21CSC305J",
      type: "LAB",
      room: "DB Lab",
      credit: "4",
    },
    "09:45 - 10:35": {
      title: "Operating Systems Lab",
      code: "21CSC306J",
      type: "LAB",
      room: "OS Lab",
      credit: "4",
    },
    "10:40 - 11:30": {
      title: "Operating Systems Lab",
      code: "21CSC306J",
      type: "LAB",
      room: "OS Lab",
      credit: "4",
    },
    "11:35 - 12:25": {
      title: "Computer Networks",
      code: "21CSC302J",
      type: "Theory",
      room: "TP101",
      credit: "4",
    },
  },
};

export const mockMarks = [
  {
    name: "Computer Networks",
    code: "21CSC302J",
    type: "Theory",
    marks: [
      { name: "CT1", mark: "14", total: "15" },
      { name: "CT2", mark: "13", total: "15" },
    ],
    credit: "4",
    total: "27.00/30",
  },
  {
    name: "Software Engineering",
    code: "21CSC303J",
    type: "Theory",
    marks: [
      { name: "CT1", mark: "15", total: "15" },
      { name: "CT2", mark: "14", total: "15" },
    ],
    credit: "4",
    total: "29.00/30",
  },
  {
    name: "Artificial Intelligence",
    code: "21CSC304J",
    type: "Theory",
    marks: [
      { name: "CT1", mark: "12", total: "15" },
      { name: "CT2", mark: "15", total: "15" },
    ],
    credit: "4",
    total: "27.00/30",
  },
  {
    name: "Database Management Systems",
    code: "21CSC305J",
    type: "Theory",
    marks: [
      { name: "CT1", mark: "10", total: "15" },
      { name: "CT2", mark: "11", total: "15" },
    ],
    credit: "4",
    total: "21.00/30",
  },
  {
    name: "Operating Systems",
    code: "21CSC306J",
    type: "Theory",
    marks: [
      { name: "CT1", mark: "13.5", total: "15" },
      { name: "CT2", mark: "14.5", total: "15" },
    ],
    credit: "4",
    total: "28.00/30",
  },
  {
    name: "Web Programming",
    code: "21CSC307J",
    type: "Theory",
    marks: [
      { name: "CT1", mark: "15", total: "15" },
      { name: "CT2", mark: "15", total: "15" },
    ],
    credit: "4",
    total: "30.00/30",
  },
];

export const mockDayorder = "1";

export const mockPlanner = {
  January: [
    { date: "01", day: "Mon", sp: "New Year", dayo: "-" },
    { date: "02", day: "Tue", sp: "", dayo: "1" },
  ],
};
